### PR TITLE
Tournaments in frontend

### PR DESCRIPTION
**Pull request by mhib**

### CODE REVIEW

**Comment by wojtowicz** [comment]
@mhib please rebase

**Comment by mhib** [comment]
@wojtowicz Done

**Comment by wojtowicz** [comment]
Your way to build menu is not correct. I will push correct template to menu on different branch and based on this you can rebase and do it properly

**Comment by wojtowicz** [comment]
Hi,

I think you have to a little bit reorgnize your code. Your approach to prepare menu was wrong. I already added menu. You can rebase and use this menu from master. I hope you will not have much work. If you will have any problems with rebasing and reimplementing this let me know.

**Pull request closed without merging**
